# Example Site settings

google_analytics: UA-113001299-1

header_pages:
  - index.md
  - about.md
  - contact.md	
footer: 'follow us on <a href="https://twitter.com/zombiepr0cess">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

url: "https://zombiepr0cess.github.io/"

plugins:
  - jekyll-seo-tag
